@extends('layouts.app')
@section('title', 'Create Client')
@section('content')
<style>
.profile-studio{--purple:#6D28D9;--deep:#3B0764;--soft:#F5F3FF;--line:#E7E1EC;max-width:1080px;margin:0 auto;background:#fff}.studio-header{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;padding:5px 2px 22px;border-bottom:1px solid var(--line);margin-bottom:20px}.back-link{display:inline-flex;align-items:center;gap:7px;color:#6F6676;text-decoration:none;font-size:.72rem;font-weight:800}.header-kicker{margin-top:14px;color:var(--purple);font-size:.65rem;font-weight:850;letter-spacing:.13em;text-transform:uppercase}.studio-header h1{margin:5px 0 0;color:#271D2E;font-size:clamp(1.8rem,3vw,2.35rem);letter-spacing:-.055em}.header-note{max-width:260px;color:#8B8390;font-size:.72rem;line-height:1.55;text-align:right}
.studio-shell{display:grid;grid-template-columns:300px minmax(0,1fr);overflow:hidden;background:#fff;border:1px solid var(--line);border-radius:20px;box-shadow:0 12px 38px rgba(59,7,100,.08)}.identity-panel{position:relative;padding:34px 28px;color:#fff;background:linear-gradient(155deg,#3B0764 0%,#5B21B6 58%,#7C3AED 100%);overflow:hidden}.identity-panel::after{content:'';position:absolute;right:-65px;bottom:-65px;width:190px;height:190px;border:1px solid rgba(255,255,255,.16);border-radius:50%}.panel-label{position:relative;color:#DDD6FE;font-size:.62rem;font-weight:850;letter-spacing:.12em;text-transform:uppercase}.portrait-input{display:none}.portrait{position:relative;z-index:1;width:142px;height:166px;display:grid;place-items:center;overflow:hidden;margin:34px auto 15px;color:#DDD6FE;background:rgba(255,255,255,.1);border:1.5px dashed rgba(255,255,255,.55);border-radius:71px 71px 17px 17px;cursor:pointer;transition:.2s}.portrait:hover{background:rgba(255,255,255,.16)}.portrait img{width:100%;height:100%;object-fit:cover}.photo-action{position:relative;z-index:1;display:block;text-align:center;color:#fff;font-size:.73rem;font-weight:800;cursor:pointer}.photo-help{position:relative;z-index:1;margin:7px 0 30px;text-align:center;color:#D8CCEA;font-size:.62rem}.panel-divider{height:1px;margin:24px 0;background:rgba(255,255,255,.17)}.panel-tip{position:relative;display:flex;gap:9px;color:#EDE9FE;font-size:.68rem;line-height:1.55}.tip-number{width:20px;height:20px;display:grid;place-items:center;flex:0 0 auto;border:1px solid rgba(255,255,255,.35);border-radius:50%;font-size:.58rem;font-weight:850}
.details-panel{padding:32px 36px;background:#fff}.form-section{padding-bottom:26px;margin-bottom:25px;border-bottom:1px solid var(--line)}.section-heading{display:flex;align-items:center;gap:10px;margin-bottom:19px}.section-number{width:27px;height:27px;display:grid;place-items:center;color:var(--deep);background:var(--soft);border:1px solid #DDD6FE;border-radius:8px;font-size:.62rem;font-weight:850}.section-heading h2{margin:0;color:#312637;font-size:.92rem}.field-grid{display:grid;grid-template-columns:1fr 1fr;gap:17px}.field.full{grid-column:1/-1}.field label{display:block;margin-bottom:7px;color:#574E5E;font-size:.66rem;font-weight:850;letter-spacing:.055em;text-transform:uppercase}.field input,.field textarea{width:100%;padding:11px 13px;color:#261D2D;background:#fff!important;border:1px solid #E3DDE7;border-radius:9px;outline:none}.field input:focus,.field textarea:focus{border-color:var(--purple);box-shadow:0 0 0 3px rgba(109,40,217,.09)}.field textarea{min-height:100px;resize:vertical}.field-error{display:block;margin-top:5px;color:var(--purple);font-size:.68rem}.social-item{display:flex;gap:8px;margin-bottom:8px}.social-item input{flex:1}.remove-social{width:42px;display:grid;place-items:center;color:var(--purple);background:#fff;border:1px solid #DDD6FE;border-radius:9px;cursor:pointer}.add-social{display:inline-flex;align-items:center;gap:5px;padding:4px 0;color:var(--purple);background:none;border:0;font-size:.7rem;font-weight:850;cursor:pointer}.studio-actions{display:flex;align-items:center;justify-content:flex-end;gap:10px}.cancel-action{padding:11px 15px;color:#6E6674;text-decoration:none;font-size:.74rem;font-weight:800}.save-action{min-height:44px;padding:0 20px;color:#fff!important;background:var(--purple)!important;border:0;border-radius:9px;font-size:.76rem;font-weight:850;cursor:pointer;box-shadow:0 7px 18px rgba(109,40,217,.2)}
@media(max-width:760px){.studio-header{align-items:flex-start;flex-direction:column}.header-note{text-align:left}.studio-shell{grid-template-columns:1fr}.identity-panel{padding:27px 22px}.portrait{margin-top:24px}.panel-divider,.panel-tip{display:none}.details-panel{padding:27px 21px}.field-grid{grid-template-columns:1fr}.field.full{grid-column:auto}.studio-actions{align-items:stretch;flex-direction:column-reverse}.cancel-action{text-align:center}.save-action{width:100%}}
</style>

<div class="profile-studio">
    <header class="studio-header"><div><a class="back-link" href="{{ route('customers.index') }}">← Back to clients</a><div class="header-kicker">New client profile</div><h1>Welcome someone new</h1></div><p class="header-note">Create a useful profile now; visits, invoices and spending history will update automatically.</p></header>
    <form class="studio-shell" action="{{ route('customers.store') }}" method="POST" enctype="multipart/form-data">@csrf
        <aside class="identity-panel"><div class="panel-label">Client identity</div><input class="portrait-input" type="file" name="image" id="imageInput" accept="image/*"><label class="portrait" for="imageInput" id="imgPreview"><svg width="38" height="38" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0116 0"/><path d="M19 3v4m-2-2h4"/></svg></label><label class="photo-action" for="imageInput">Choose a client photo</label><div class="photo-help">Optional · JPG or PNG · up to 2 MB</div><div class="panel-divider"></div><div class="panel-tip"><span class="tip-number">1</span><span>Use the contact details your reception team will recognise during booking.</span></div><div class="panel-tip" style="margin-top:15px"><span class="tip-number">2</span><span>Keep sensitive preferences in private salon notes.</span></div></aside>
        <div class="details-panel">
            <section class="form-section"><div class="section-heading"><span class="section-number">01</span><h2>Contact essentials</h2></div><div class="field-grid"><div class="field"><label>Full name *</label><input type="text" name="name" value="{{ old('name') }}" placeholder="Client's full name" required>@error('name')<span class="field-error">{{ $message }}</span>@enderror</div><div class="field"><label>Phone number *</label><input type="text" name="phone" value="{{ old('phone') }}" placeholder="+92 300 1234567" required>@error('phone')<span class="field-error">{{ $message }}</span>@enderror</div><div class="field full"><label>Email address</label><input type="email" name="email" value="{{ old('email') }}" placeholder="client@example.com">@error('email')<span class="field-error">{{ $message }}</span>@enderror</div></div></section>
            <section class="form-section"><div class="section-heading"><span class="section-number">02</span><h2>Social profiles</h2></div><div id="social_list"><div class="social-item"><input type="text" name="social_media[]" value="{{ old('social_media.0') }}" placeholder="Instagram, Facebook or another handle"><button class="remove-social" type="button" style="visibility:hidden">×</button></div></div><button type="button" class="add-social" onclick="addSocialField()">＋ Add another handle</button></section>
            <section class="form-section"><div class="section-heading"><span class="section-number">03</span><h2>Salon notes</h2></div><div class="field"><label>Private notes</label><textarea name="notes" placeholder="Preferences, sensitivities, formulas or useful context...">{{ old('notes') }}</textarea></div></section>
            <div class="studio-actions"><a class="cancel-action" href="{{ route('customers.index') }}">Cancel</a><button class="save-action" type="submit">Create client profile</button></div>
        </div>
    </form>
</div>
<script>
function addSocialField(){const row=document.createElement('div');row.className='social-item';row.innerHTML='<input type="text" name="social_media[]" placeholder="Social profile or handle"><button type="button" class="remove-social" onclick="this.parentElement.remove()">×</button>';document.getElementById('social_list').appendChild(row)}
document.getElementById('imageInput').addEventListener('change',function(){const file=this.files[0];if(!file)return;const reader=new FileReader();reader.onload=e=>document.getElementById('imgPreview').innerHTML=`<img src="${e.target.result}" alt="Client preview">`;reader.readAsDataURL(file)})
</script>
@endsection
