@extends('layouts.app')
@section('title', 'New Supplier')
@section('content')
<style>
:root{--y1:#6D28D9;--y2:#EDE9FE;--yd:#6D28D9;--ydark:#4C1D95;--ybg:#F5F3FF}.form-wrap{max-width:720px;margin:0 auto}.form-header{display:flex;align-items:center;gap:12px;margin-bottom:22px}.back-btn{width:36px;height:36px;border-radius:9px;border:1.5px solid #e4e4e7;background:#fff;display:flex;align-items:center;justify-content:center;color:#71717a;text-decoration:none}.pg-title{font-size:1.4rem;font-weight:800;color:#18181b;margin-bottom:3px}.pg-sub{font-size:.85rem;color:#71717a}.form-card{background:#fff;border:1.5px solid #DDD6FE;border-radius:18px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,.05)}.form-section{padding:22px 26px;border-bottom:1px solid #f4f4f5}.section-title{font-size:.72rem;font-weight:700;color:#a1a1aa;text-transform:uppercase;letter-spacing:.1em;margin-bottom:16px;display:flex;align-items:center;gap:7px}.section-icon{width:22px;height:22px;border-radius:6px;background:var(--y2);display:flex;align-items:center;justify-content:center;color:var(--ydark)}.f-grid-2{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-bottom:14px}.f-row{margin-bottom:14px}.f-label{display:block;font-size:.78rem;font-weight:600;color:#374151;margin-bottom:7px}.f-input{width:100%;padding:10px 13px;border:1.5px solid #DDD6FE;border-radius:10px;font-size:.875rem;color:#18181b;background:var(--ybg);outline:none}.f-input:focus{border-color:var(--y1);background:#fff}.f-input::placeholder{color:#a1a1aa}textarea.f-input{resize:vertical;min-height:90px}.check-row{display:flex;align-items:center;gap:8px;cursor:pointer}.check-row input{accent-color:var(--ydark)}.check-lbl{font-size:.875rem;font-weight:600;color:#374151}.err{font-size:.72rem;color:#4C1D95;margin-top:4px}.form-footer{padding:18px 26px;display:flex;gap:10px;justify-content:flex-end}.btn-cancel{padding:10px 22px;border:1.5px solid #e4e4e7;background:#fff;border-radius:10px;color:#71717a;text-decoration:none}.btn-save{padding:10px 22px;border:none;background:#6D28D9;border-radius:10px;color:#fff;font-weight:800;cursor:pointer}@media(max-width:640px){.f-grid-2{grid-template-columns:1fr}}
</style>
<div class="form-wrap"><div class="form-header"><a href="{{ route('suppliers.index') }}" class="back-btn">←</a><div><div class="pg-title">New Supplier</div><div class="pg-sub">Register a new vendor or supply partner</div></div></div><div class="form-card"><form action="{{ route('suppliers.store') }}" method="POST">@csrf
<div class="form-section"><div class="section-title"><div class="section-icon">01</div>Company Information</div><div class="f-row"><label class="f-label">Company Name *</label><input type="text" name="name" value="{{ old('name') }}" required class="f-input" placeholder="e.g. Prestige Beauty Supplies">@error('name')<div class="err">{{ $message }}</div>@enderror</div><div class="f-row"><label class="f-label">Address</label><textarea name="address" class="f-input" placeholder="Full registered address…">{{ old('address') }}</textarea></div><label class="check-row"><input type="checkbox" name="is_active" value="1" {{ old('is_active',true)?'checked':'' }}><span class="check-lbl">Active supplier</span></label></div>
<div class="form-section"><div class="section-title"><div class="section-icon">02</div>Contact Details</div><div class="f-grid-2"><div><label class="f-label">Contact Person</label><input type="text" name="contact_person" value="{{ old('contact_person') }}" class="f-input" placeholder="Full name"></div><div><label class="f-label">Phone Number</label><input type="tel" name="phone" value="{{ old('phone') }}" class="f-input" placeholder="+92 300 1234567"></div></div><div class="f-row" style="margin:0"><label class="f-label">Email Address</label><input type="email" name="email" value="{{ old('email') }}" class="f-input" placeholder="vendor@example.com"></div></div>
<div class="form-section"><div class="section-title"><div class="section-icon">03</div>Payment Terms</div><select name="payment_terms" class="f-input"><option value="cod" {{ old('payment_terms')==='cod'?'selected':'' }}>Cash on Delivery (COD)</option><option value="net_15" {{ old('payment_terms')==='net_15'?'selected':'' }}>Net 15 Days</option><option value="net_30" {{ old('payment_terms','net_30')==='net_30'?'selected':'' }}>Net 30 Days</option><option value="net_60" {{ old('payment_terms')==='net_60'?'selected':'' }}>Net 60 Days</option></select></div><div class="form-footer"><a href="{{ route('suppliers.index') }}" class="btn-cancel">Cancel</a><button type="submit" class="btn-save">Create Supplier</button></div></form></div></div>
@endsection
